{
 "title": "Sample Global Load Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "transaction",
    "label": "transaction",
    "query": "SHOW TAG VALUES FROM jmeter WITH KEY = \"transaction\" "
   },
   {
    "name": "location",
    "label": "location",
    "query": "SHOW TAG VALUES FROM jmeter WITH KEY = \"location\" "
   }
  ]
 },
 "panels": [
  { "title": "Test Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Stats Per Transaction",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "transaction" ], "type": "tag" }
     ],
     "measurement": "jmeter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Transactions" ], "type": "alias" }
      ],
      [
       { "params": [ "avg" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Avg." ], "type": "alias" }
      ],
      [
       { "params": [ "pct95.0" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "p95" ], "type": "alias" }
      ],
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Max" ], "type": "alias" }
      ],
      [
       { "params": [ "min" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       },
       { "params": [ "Min" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "!=", "value": "all" }
     ]
    }
   ]
  },
  {
   "title": "TPS over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jmeter",
     "query": "select mean(TPS) *  ($__interval_ms /10000) from (SELECT sum(\"count\") as TPS FROM \"jmeter\" WHERE (\"transaction\" =~ /^$transaction$/ AND \"location\" =~ /^$location$/) AND $timeFilter GROUP BY time(10s) fill(0)) GROUP BY time($__interval), transaction;",
     "select": [
      [
       { "params": [ "hit" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=~", "value": "/^$transaction$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" }
     ]
    }
   ]
  },
  {
   "title": "P95 over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "alias": "$tag_transaction",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "transaction" ], "type": "tag" }
     ],
     "measurement": "jmeter",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "p95" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=~", "value": "/^$transaction$/" }
     ]
    }
   ]
  },
  {
   "title": "Active Devices over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "alias": "$tag_device",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jmeter",
     "query": "SELECT count(distinct(\"device\")) from (SELECT count(\"hit\") FROM \"jmeter\" WHERE  $timeFilter GROUP BY time($__interval), \"device\" fill(null)) GROUP BY time($__interval);",
     "select": [
      [
       { "params": [ "hit" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Active Threads over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jmeter",
     "query": "SELECT mean(\"maxAT\") AS threads FROM \"jmeter\" WHERE (\"location\" =~ /^$location$/) AND $timeFilter GROUP BY time($__interval), \"device\" fill(0)",
     "select": [
      [
       { "params": [ "meanAT" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=~", "value": "/^$location$/" }
     ]
    }
   ]
  },
  { "title": "World Map Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Total Transactions",
   "type": "geomap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "alias": "$tag_lat $tag_lat $tag_transaction $tag_location",
     "groupBy": [
      { "params": [ "lat" ], "type": "tag" },
      { "params": [ "lon" ], "type": "tag" },
      { "params": [ "location" ], "type": "tag" }
     ],
     "measurement": "jmeter",
     "query": "SELECT sum(\"count\") AS \"total_hits\" FROM \"jmeter\" WHERE $timeFilter GROUP BY \"lat\", \"lon\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "total_hits" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=~", "value": "/^$transaction$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" }
     ]
    }
   ]
  },
  {
   "title": "Errors",
   "type": "geomap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "alias": "$tag_lat $tag_lat",
     "groupBy": [
      { "params": [ "lat" ], "type": "tag" },
      { "params": [ "lon" ], "type": "tag" },
      { "params": [ "statut" ], "type": "tag" }
     ],
     "measurement": "jmeter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "errors" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "transaction", "operator": "=~", "value": "/^$transaction$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ko" }
     ]
    }
   ]
  },
  {
   "title": "Errors",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "alias": "$tag_transaction $tag_responseCode $tag_responseMessage",
     "groupBy": [
      { "params": [ "responseCode" ], "type": "tag" },
      { "params": [ "transaction" ], "type": "tag" },
      { "params": [ "responseMessage" ], "type": "tag" }
     ],
     "measurement": "jmeter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Count" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=~", "value": "/^$transaction$/" },
      { "condition": "AND", "key": "location", "operator": "=~", "value": "/^$location$/" },
      { "condition": "AND", "key": "responseMessage", "operator": "!=", "value": "''" }
     ]
    }
   ]
  }
 ]
}